language: ruby
rvm:
- 2.4.1
deploy:
  provider: heroku
  api_key:
    secure: tdcVnmVq5uvcF26NXjDzfIuFWUXLM5sa2WM4IWt6vphiNS65yLMBGwHKRW5EyqunYXKMTr00/hSEZ6y3Upoz4fLvkjbMEfitZa6UnnWuQLWwU0vE0gnEHl/JfuRZeDZ2nILVda4lMD2azmBzz/vgE71pYvb2a9wZO9A/ekJ/5Fy8sSTL93NrO3Ek0L1KkElYaYPD6RwDAyBl8Y8JYpLzmv6dBiYO7Wmvqy2MGBjbOmq4G5+dNU3eBWmcdhfeQLJu/WDKBWY724VSKkC7nKfXg5v3UHaS7CeIgTugAGkKVIiOag2s7LtoUoFLF6OBMhCeP9mh+3r4oiKyzWDHYC7trOE8UzHp90EfwOadB8tHiBp7UR+DAMtlmQ3n/qZL0D+0fZ8Zeybv8SNjWoikjhNey6cq/sVOOMzq5Qfz1LCgjhz6lsihB7bPeSoyRvPj3ytWHt+rb/0tVyqTQgMcR9VZJr6OmScjRVxQeEF0nY43662CbtGX7B1NZMhCeYDZz8JL4ekahDwg/YQNEtXh3FqKQRfMqJnf/MDMpL5UGQl8ewZLUacq8nMLQCpen8SiBrlFuW2QC9ceq9ny6E76DrnvMr3dvWvsIIDZnLbwr8kCdQRQmbCnVeLzfeihXpEOqfLyQGPMANvGGWjhnpjZNJKutoE3G0y5OaqduwWE/J3Itto=
